###
PUT http://localhost:3000/api/test.png?downloads=5
Content-Type: image/jpeg

< jamaica.jpg


###
PUT http://localhost:3000/api/termius.exe?key=hemmeligkode
Content-Type: binary/octet-stream

< C:\Users\aleks\Downloads\Install Termius.exe

###
PUT http://localhost:3000/api/morten.txt?key=privat
Content-Type: text/plain

Hej morten, how does it go with your exam?
